<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Kitchen Stock Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', 'Helvetica', 'Arial', sans-serif;
            font-size: 10px;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0;
        }
        .header h3 {
            font-size: 14px;
            margin: 5px 0;
            color: #555;
        }
        .header p {
            font-size: 10px;
            color: #777;
            margin: 3px 0;
        }
        .stats {
            margin-bottom: 15px;
            width: 100%;
        }
        .stats td {
            padding: 5px;
            border: 1px solid #ddd;
            background-color: #f9f9f9;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f3f4f6;
            padding: 8px;
            text-align: left;
            font-weight: bold;
            border: 1px solid #ddd;
            font-size: 9px;
        }
        td {
            padding: 6px;
            border: 1px solid #ddd;
            font-size: 9px;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .status-in-stock {
            color: #10b981;
            font-weight: bold;
        }
        .status-low-stock {
            color: #eab308;
            font-weight: bold;
        }
        .status-out-of-stock {
            color: #ef4444;
            font-weight: bold;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            font-size: 8px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>PATIO BELLA RESTAURANT</h1>
        <h3>Kitchen Stock Report</h3>
        <p>Generated on: {{ $generated_at }}</p>
        <p>Generated by: {{ $generated_by }}</p>
    </div>

    <table class="stats">
        <tr>
            <td class="text-center"><strong>Total Items</strong><br>{{ number_format($totalItems) }}</td>
            <td class="text-center"><strong>Total Issued</strong><br>{{ number_format($totalIssued) }}</td>
            <td class="text-center"><strong>Total Consumed</strong><br>{{ number_format($totalConsumed) }}</td>
            <td class="text-center"><strong>Total Returned</strong><br>{{ number_format($totalReturned) }}</td>
            <td class="text-center"><strong>Total Stock Value</strong><br>{{ number_format($totalStockValue) }}</td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Code</th>
                <th>Category</th>
                <th>Unit</th>
                <th class="text-right">Issued</th>
                <th class="text-right">Consumed</th>
                <th class="text-right">Returned</th>
                <th class="text-right">Current Stock</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($stockData as $item)
            @php
                $statusClass = '';
                $statusText = '';
                if ($item['current_stock'] <= 0) {
                    $statusClass = 'status-out-of-stock';
                    $statusText = 'Out of Stock';
                } elseif ($item['current_stock'] <= 10) {
                    $statusClass = 'status-low-stock';
                    $statusText = 'Low Stock';
                } else {
                    $statusClass = 'status-in-stock';
                    $statusText = 'In Stock';
                }
            @endphp
            <tr>
                <td>{{ $item['item_name'] }}</td>
                <td>{{ $item['item_code'] }}</td>
                <td>{{ $item['category_name'] }}</td>
                <td>{{ ucfirst($item['unit']) }}</td>
                <td class="text-right">{{ number_format($item['issued']) }}</td>
                <td class="text-right">{{ number_format($item['consumed']) }}</td>
                <td class="text-right">{{ number_format($item['returned']) }}</td>
                <td class="text-right"><strong>{{ number_format($item['current_stock']) }}</strong></td>
                <td><span class="{{ $statusClass }}">{{ $statusText }}</span></td>
            </tr>
            @empty
            <tr>
                <td colspan="9" class="text-center">No stock data available</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>*** End of Report ***</p>
        <p>This report was generated automatically by PatioBella POS System</p>
    </div>
</body>
</html>
