<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;

class ReportsExport implements FromArray, WithHeadings, WithStyles, WithColumnWidths
{
    protected $data;
    protected $title;
    protected $reportType;

    public function __construct($data, $title, $reportType)
    {
        $this->data = $data;
        $this->title = $title;
        $this->reportType = $reportType;
    }

    public function array(): array
    {
        $exportData = [];

        // Header
        $exportData[] = [strtoupper($this->title)];
        $exportData[] = ['Generated Date: ' . now()->format('F d, Y H:i:s')];
        $exportData[] = [];
        $exportData[] = [];

        // Headers
        $headers = $this->getHeaders();
        $exportData[] = $headers;

        // Data rows
        $rows = $this->getDataRows();
        foreach ($rows as $row) {
            $exportData[] = $row;
        }

        // Footer
        $exportData[] = [];
        $exportData[] = [];
        $exportData[] = ['Report generated by Patiobella Management System'];

        return $exportData;
    }

    public function headings(): array
    {
        return [];
    }

    private function getHeaders(): array
    {
        switch ($this->reportType) {
            case 'stock_valuation':
                return ['Item Code', 'Item Name', 'Category', 'UOM', 'Quantity', 'Avg Cost (UGX)', 'Total Value (UGX)'];
            case 'low_stock':
                return ['Item Code', 'Item Name', 'Category', 'UOM', 'Min Stock', 'Current Stock', 'Status'];
            case 'expiring_batches':
                return ['Batch Number', 'Item Name', 'Expiry Date', 'Remaining Qty', 'UOM', 'Status'];
            case 'department_stock':
                return ['Department', 'Item Code', 'Item Name', 'UOM', 'Current Stock'];
            case 'department_consumption':
                return ['Item Name', 'UOM', 'Total Used'];
            case 'performance':
                return ['Report #', 'Department', 'Date', 'Sales (UGX)', 'COGS (UGX)', 'Profit (UGX)', 'Gifts (UGX)', 'Margin %'];
            default:
                return ['Item Code', 'Item Name', 'Category', 'UOM', 'Quantity', 'Avg Cost (UGX)', 'Total Value (UGX)'];
        }
    }

    private function getDataRows(): array
    {
        $rows = [];

        switch ($this->reportType) {
            case 'stock_valuation':
                foreach ($this->data['items'] as $item) {
                    $rows[] = [
                        $item->item_code,
                        $item->name,
                        $item->category ?? 'N/A',
                        $item->unit_of_measurement,
                        number_format($item->total_quantity, 2),
                        number_format($item->avg_cost, 2),
                        number_format($item->total_value, 2),
                    ];
                }
                if (!empty($this->data['summary'])) {
                    $rows[] = [];
                    $rows[] = ['', '', '', '', 'TOTAL', '', number_format($this->data['summary']['total_value'], 2)];
                }
                break;

            case 'low_stock':
                foreach ($this->data['items'] as $item) {
                    $status = $item->current_stock <= 0 ? 'Out of Stock' : 'Low Stock';
                    $rows[] = [
                        $item->item_code,
                        $item->name,
                        $item->category ?? 'N/A',
                        $item->unit_of_measurement,
                        number_format($item->minimum_stock, 2),
                        number_format($item->current_stock, 2),
                        $status,
                    ];
                }
                break;

            case 'expiring_batches':
                foreach ($this->data['batches'] as $batch) {
                    $daysLeft = now()->diffInDays($batch->expiry_date, false);
                    $status = $daysLeft <= 7 ? 'Critical' : ($daysLeft <= 14 ? 'Warning' : 'Normal');
                    $rows[] = [
                        $batch->batch_number,
                        $batch->inventoryItem->name ?? 'N/A',
                        $batch->expiry_date->format('Y-m-d'),
                        number_format($batch->remaining_quantity, 2),
                        $batch->unit_of_measurement,
                        $status,
                    ];
                }
                break;

            case 'department_stock':
                foreach ($this->data['stock'] as $stock) {
                    $rows[] = [
                        $stock->department,
                        $stock->item_code,
                        $stock->item_name,
                        $stock->unit_of_measurement,
                        number_format($stock->current_stock, 2),
                    ];
                }
                break;

            case 'department_consumption':
                foreach ($this->data['consumption'] as $item) {
                    $rows[] = [
                        $item->name,
                        $item->unit_of_measurement,
                        number_format($item->total_used, 2),
                    ];
                }
                break;

            case 'performance':
                foreach ($this->data['reports'] as $report) {
                    $rows[] = [
                        $report->report_number,
                        $report->department->name ?? 'N/A',
                        $report->report_date->format('Y-m-d'),
                        number_format($report->total_sales, 2),
                        number_format($report->total_cogs, 2),
                        number_format($report->total_profit, 2),
                        number_format($report->gifts_amount ?? 0, 2),
                        number_format($report->profit_margin, 2) . '%',
                    ];
                }
                if (!empty($this->data['summary'])) {
                    $rows[] = [];
                    $rows[] = ['SUMMARY', '', '', number_format($this->data['summary']['total_sales'], 2), number_format($this->data['summary']['total_cogs'], 2), number_format($this->data['summary']['total_profit'], 2), number_format($this->data['summary']['total_gifts'], 2), number_format($this->data['summary']['avg_margin'], 2) . '%'];
                }
                break;

            default:
                foreach ($this->data['items'] as $item) {
                    $rows[] = [
                        $item->item_code,
                        $item->name,
                        $item->category ?? 'N/A',
                        $item->unit_of_measurement,
                        number_format($item->total_quantity, 2),
                        number_format($item->avg_cost, 2),
                        number_format($item->total_value, 2),
                    ];
                }
        }

        return $rows;
    }

    public function styles(Worksheet $sheet)
    {
        // Title style
        $sheet->mergeCells('A1:G1');
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(16);
        $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        // Date row style
        $sheet->mergeCells('A2:G2');
        $sheet->getStyle('A2')->getFont()->setSize(10);
        $sheet->getStyle('A2')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        // Headers style
        $headerRow = 5;
        $sheet->getStyle('A' . $headerRow . ':G' . $headerRow)->getFont()->setBold(true);
        $sheet->getStyle('A' . $headerRow . ':G' . $headerRow)->getFill()->setFillType(Fill::FILL_SOLID);
        $sheet->getStyle('A' . $headerRow . ':G' . $headerRow)->getFill()->getStartColor()->setARGB('FF4472C4');
        $sheet->getStyle('A' . $headerRow . ':G' . $headerRow)->getFont()->getColor()->setARGB('FFFFFFFF');
        $sheet->getStyle('A' . $headerRow . ':G' . $headerRow)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        // Add borders to all data
        $highestRow = $sheet->getHighestRow();
        $sheet->getStyle('A1:G' . $highestRow)->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);

        // Auto-size columns
        foreach (range('A', 'G') as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(true);
        }

        return [];
    }

    public function columnWidths(): array
    {
        return [
            'A' => 20,
            'B' => 30,
            'C' => 20,
            'D' => 15,
            'E' => 20,
            'F' => 20,
            'G' => 20,
        ];
    }
}
